language: rust

cache:
  - apt
  - cargo

install:
  - command -q mdbook >/dev/null 2>&1 || cargo install mdbook
  - command -q mdbook-linkcheck >/dev/null 2>&1 || cargo install mdbook-linkcheck

script:
  - cargo build --verbose
  - cargo test --verbose

before_deploy:
  - cargo doc
  - mdbook build book
  - mkdir public
  - cp -r target/doc public/
  - cp -r target/book public/
  - echo "<meta http-equiv=refresh content=0;url=book/index.html>" > public/index.html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  keep-history: false  
  local-dir: public
  on:
    branch: master